version: "3.9"

services:
  jobmanager:
    image: flink:1.17.2-scala_2.12
    hostname: jobmanager
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
          jobmanager.rpc.address: jobmanager
          rest.address: 0.0.0.0
          rest.port: 8081
    ports:
      - "8081:8081"

  taskmanager:
    image: flink:1.17.2-scala_2.12
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
          jobmanager.rpc.address: jobmanager
          taskmanager.numberOfTaskSlots: 4

  flink-sql-proxy:
    build: .
    environment:
      FLINK_REST_URL: http://jobmanager:8081
      FLINK_APPLICATION_NAME: sql-runner
      AUTH_TOKEN: hackathon
    ports:
      - "8080:8080"
    depends_on:
      - jobmanager
