version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/ # persistence
    ports:
      - 5432:5432
volumes:
  postgres-data: